name: test
on:
    push:
        branches-ignore:
            - master
        paths-ignore:
            - .git*
            - '**.md'
    pull_request:
        branches:
            - master
        paths-ignore:
            - .git*
            - '**.md'
jobs:
    test:
        name: 'test: ${{matrix.os}}'
        runs-on: ${{matrix.os}}-latest
        strategy:
            fail-fast: true
            matrix:
                os:
                    - ubuntu
                    - macos
                    - windows
        steps:
            - name: clone repository
              uses: actions/checkout@v4
            - name: install deno
              uses: denoland/setup-deno@v2
              with:
                deno-version: v2.x
            - name: run test
              run: deno test -A --parallel --doc ./test